server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    #gateway配置
#    gateway:
#      #路由规则,数据类型为List
#      routes:
#        #路由的唯一标识
#        - id: order_route
#          #需要转发的地址
#          uri: lb://order-service
#          #断言规则,用于路由规则的匹配
#          predicates:
#            - Path=/order/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public